#!/usr/bin/python
import os
import sys
import time
import unittest
import telnetlib
import re

import utils
import ixia
import tmsData
sys.path.append(os.path.join('fsal', 'lib'))
import fsalUtils


#### initialization ####
conf = None
log = None
dut = None
def initialize():
	fsalUtils.initialize()
	global conf
	conf = utils.conf
	global log
	log = utils.log
	global dut
	dut = fsalUtils.dut
	ixia.initialize()
	log.debug('Successfully initialised fsal project')


def cleanup():
	pass


#### unittest classes ####
class TestResult(fsalUtils.TestResult):
	def getDetails(self, testName):
		(tmsId, description) = tmsData.tmsDict.get(testName, ('Unknown', 'Unknown'))
		description = description.replace(',', ' ')
		return(tmsId, description)


#### utilities ####
